### ISSUE TITLE
circ.edges.pair_edges(pre_node, post_node, properties) leads to Error

### ISSUE THREAD

**Issue by MWolfR** [BlueBrain/snap#203]
I run the following:
![image](https://user-images.githubusercontent.com/47882990/236387580-070d087c-cf5c-4d25-b24f-9293e4a9773b.png)

which leads to a BluepySnapError with the following description:

```
File ~/venvs/bpsnap/lib/python3.10/site-packages/bluepysnap/network.py:57, in NetworkObject.property_dtypes.<locals>._update(d, index, value)
     55 def _update(d, index, value):
     56     if d.setdefault(index, value) != value:
---> 57         raise BluepySnapError(
     58             f"Same property with different dtype. {index}: {value}!= {d[index]}"
     59         )

BluepySnapError: Same property with different dtype. afferent_section_id: int16!= int64
```

Source seems to be section ids being represented by different data types in different EdgePopulations, but I think Snap should handle that gracefully.

**Comment by MWolfR** [comment]
I note that this seems to be conceptually the same issue we encountered for the NodePopulations, just for edges instead.

**Comment by GianlucaFicarelli** [comment]
We had some discussion about this, and a possible approach is to extend the categories when they differ across the populations, and let Pandas concatenate and handle the other types.

Moreover, when the selected nodes or edges belong to a single population, we can also do an internal optimization, by returning just the DataFrame obtained from that population, without concatenation.

Additionally, we can provide a method similar to `.get()`, returning an iterable of DataFrames, rather than a concatenation. In some cases it may be more useful, and it should be more performant than concatenating the DataFrames.

We are also considering to remove the method [property_dtypes](https://github.com/BlueBrain/snap/blob/bc870f6b89b9551db8e2cebc5fefde8b4ecb6a8c/bluepysnap/network.py#L52), unless it's proven to be useful as a public method, because it's the source of the issue.
