### ISSUE TITLE
add kwarg to `firing_rate_histogram` to allow considering gids outside the report

### ISSUE THREAD

**Issue by joni-herttuainen** [BlueBrain/snap#263]
`firing_rate_histogram` is limited to only consider gids within the report (see: [here](https://github.com/BlueBrain/snap/blob/16986bf0b78f73f016335751ca9042496fa345e5/bluepysnap/_plotting.py#L82)).

`bluepy` did not have the same behavior in it's implementation of the plot. Therefore, to ease the comparison to simulation runs done in `bluepy`, it was suggested to add a keyword argument to have similar behavior. 

Another motivation is to get an overview of the entire population firing behaviour / firing rates.

**Comment by mgeplf** [comment]
I remember there being a lot of back and forth about this, and how having arguments like this will blow up over time as everyone has their own desires.
In light of that, can you check if there isn't another way to include all gids, instead of just the ones in the report? I don't see one, but it's worth looking.
Otherwise, adding an argument makes sense to me; perhaps it can be a function that is passed in that `filters` desired GIDs, with the default function being the current behavior?

**Comment by joni-herttuainen** [comment]
Yeah, I remember Thomas not being happy about the plots being part of the package in the first place. Reasoning being that it's downright impossible to create a plot that works for everyone in every case and it will need to be tweaked much like here now. 

I'll take a further look and see what can be done and then give a deep thought to "should it be done".

**Comment by mgeplf** [comment]
>  "should it be done".

Having plots, including `firing_rate_histogram` is required, but yeah, have a look on how best to be able to include gids outside of the report.
